#!/usr/bin/env bash
source "$(dirname "$0")/common.sh"
require_parallelism_cap
cd "${ROOT_DIR}"

./mill ${NOVA_MILL_OPTS:-} __.compile
./mill ${NOVA_MILL_OPTS:-} test
./mill ${NOVA_MILL_OPTS:-} emitVerilog
bash scripts/run_isa_tests.sh
bash scripts/run_spike_diff.sh
bash scripts/run_freertos_demo.sh

toolchain_commit="not-present"
spike_commit="not-present"
freertos_commit="not-present"

if [[ -d tools/src/riscv-gnu-toolchain/.git ]]; then
  toolchain_commit="$(git -C tools/src/riscv-gnu-toolchain rev-parse HEAD)"
fi
if [[ -d tools/src/riscv-isa-sim/.git ]]; then
  spike_commit="$(git -C tools/src/riscv-isa-sim rev-parse HEAD)"
fi
if git -C third_party/FreeRTOS-Kernel rev-parse --git-dir >/dev/null 2>&1; then
  freertos_commit="$(git -C third_party/FreeRTOS-Kernel rev-parse HEAD)"
fi

gcc_version="not-present"
if [[ -x tools/riscv/bin/riscv32-unknown-elf-gcc ]]; then
  gcc_version="$(tools/riscv/bin/riscv32-unknown-elf-gcc --version | head -n 1)"
fi

spike_version="installed"
if [[ -x tools/spike/bin/spike ]]; then
  spike_version="$(tools/spike/bin/spike --help 2>&1 | sed -n '1p')"
fi

spike_summary="$(cat out/spike-diff/summary.txt)"
freertos_summary="$(cat out/freertos/summary.txt)"

cat > docs/VERIFICATION_REPORT.md <<REPORT
# NovaV1 Verification Report

Generated by scripts/run_regression.sh.

## Results
- Mill compile: PASS
- Scala/Chisel elaboration and execution tests: PASS
- Verilog emission: PASS
- Directed ISA ChiselSim tests: PASS (out/isa-tests/summary.txt)
- Spike per-retire differential: PASS (out/spike-diff/summary.txt)
- FreeRTOS Spike reference and Nova ChiselSim ELF run: PASS (out/freertos/summary.txt)
- Static repository checks: PASS

## Tool Evidence
- RISC-V GNU toolchain superproject: ${toolchain_commit}
- RISC-V GCC: ${gcc_version}
- Spike source: ${spike_commit}
- Spike binary: ${spike_version}
- FreeRTOS-Kernel: ${freertos_commit} (required tag V11.1.0)
- ISA string: rv32imac_zicsr_zifencei_zicntr_zba_zbb_zbs
- ABI: ilp32
- Parallelism cap: MAKEFLAGS=-j4, CMAKE_BUILD_PARALLEL_LEVEL=4, NINJAFLAGS=-j4

## Directed ISA Evidence
The AXI-backed ChiselSim suite in NovaV1ExecutionSpec executes instruction streams through the SoC-grade NovaV1 mem/reg/platform/debug IO and checks architectural trace results. The assembly ELFs under sim/isa cover RV32I, M, A, C, Zicsr/Zicntr, Zifencei, Zba/Zbb/Zbs, traps, and privileged timer behavior. The directed tests cover x0 behavior, sign and zero extension, branch and jump targets, JALR bit clearing, compressed and halfword-crossing instruction fetch, CSR suppression, division corner cases, AXI4 LR/SC and AMO exclusive flows, byte lanes, little-endian memory, misalignment, synchronous traps, AXI4-Lite control registers, debug hart status, and timer interrupts.

## Spike Evidence
scripts/run_spike_diff.sh compiles the directed and deterministic random ELFs with the local RISC-V GCC, runs each on the NovaV1 ChiselSim ELF runner, runs each comparable ELF on Spike with --isa=rv32imac_zicsr_zifencei_zicntr_zba_zbb_zbs --log-commits, and compares per-retire PC, raw instruction bits, rd writes, reconstructed integer registers, selected CSR accesses, traps where comparable, and memory side effects. The only accepted masks are HTIF, CLINT/timer, and EEI-specific trap behavior.

Spike summary artifact:
${spike_summary}

## FreeRTOS Evidence
scripts/run_freertos_demo.sh builds the NovaV1 FreeRTOS demo against FreeRTOS-Kernel V11.1.0, executes the ELF on Spike to the HTIF pass signature, then executes the same ELF on the NovaV1 ChiselSim ELF runner. The Nova run passes only when tohost == 1, nova_pass_signature == 0x4e4f5641, a machine timer interrupt is observed, no unexpected synchronous trap occurs, and scheduler/task/queue/semaphore/critical-section progress counters advance.

FreeRTOS summary artifact:
${freertos_summary}

## One-Cycle Evidence
The Chisel assertions and NovaV1ExecutionSpec verify that debug retire trace events are non-dropping, x0 writes are suppressed, aligned AXI4 fetch assembles compressed and halfword-crossing instructions, and AXI4 LSU sequencing preserves memory semantics. Multiply/divide, CSR, compressed, bitmanip, and non-memory execute paths retire after fetch without iterative helper state; AXI4 bus waits, AMO exclusive retries, and Decoupled debug-retire backpressure are modeled as front-end/LSU/debug wait states.

## Assumptions
- The narrowed one-cycle claim applies after fetch and any required LSU result are available; AXI waits are explicit architectural stalls.
- Spike comparison masks only documented HTIF, CLINT/timer, and EEI trap differences.
- The FreeRTOS timer rate is configured for deterministic simulation with configCPU_CLOCK_HZ=1000000 and configTICK_RATE_HZ=1000.
REPORT

bash scripts/static_checks.sh

echo "Regression completed; see docs/VERIFICATION_REPORT.md"
